name: CI

on:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.78.0

jobs:
  bench-hyperfine:
    name: Hyperfine
    runs-on: ubuntu-latest
    env:
      MLIR_SYS_180_PREFIX: /usr/lib/llvm-18/
      LLVM_SYS_180_PREFIX: /usr/lib/llvm-18/
      TABLEGEN_180_PREFIX: /usr/lib/llvm-18/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Add LLVM deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install LLVM
        run: sudo apt-get install llvm-18 llvm-18-dev llvm-18-runtime clang-18 clang-tools-18 lld-18 libpolly-18-dev libmlir-18-dev mlir-18-tools

      - name: Install hyperfine
        uses: taiki-e/install-action@v2
        with:
          tool: hyperfine@1.16

      - name: Run benchmarks
        run: make revm-comparison